### ISSUE TITLE
Bug: s_out points don't match with max_fit

### ISSUE THREAD

**Issue by garland-culbreth** [bradbell/at_cascade#8]
A fit had s_out points which didn't match up with the max_fit setting specified.
The file path to the folder where this issue occurred is in the slack thread, submitting as a bug report after the meeting this morning.

**Comment by bradbell** [comment]
@garland-culbreth You should mention where the files are that demonstrate this problem and the fact that one must be a member of ihme to access these files.

**Comment by bradbell** [comment]
I have been able to reproduce the problem by counting the number of hold outs for the following example:
https://dismod-at.readthedocs.io/user_hold_out_2.py.html#user-hold-out-2-py-name
